### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Kiruscha** [Eclip5eLP/TemtemLumaBot#1]
Hello.
Bot is just spamming A+D really fast for me. Changing settings doesnt change the A+D spam. 
Also doesnt recognize when battle starts. :(

**Comment by Eclip5eLP** [comment]
Is your resolution 1920x1080? If so just change "resolution" to 0 inside the settings, thats should fix it detecting battles :)
Just place your character inside some grass and then start it. Its supposed to spam A+D until it finds a battle. Its completely working by analyzing the visuals and its rly hard to make it recognize grass and go to it ^^'

**Comment by Joshgriste** [comment]
Having the same issue, doesn't detect its entering a battle and just continues to spam a+d
